In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import sklearn
import keras.backend as K
from keras.models import Sequential
from keras.layers import Dense
from sklearn.ensemble import RandomForestRegressor
from sklearn import linear_model
from sklearn import svm
import scipy.io
import pickle

In [139]:
x = np.array([[1,2,3],
     [4,5,6],
     [7,8,9],
     [10, 11, 12]])

new_array = np.empty(np.shape(x))
for i in range(np.shape(x)[1]):
    print(x[:,i])
    print(normalize(x[:,i]))
    new_array[:,i] = normalize(x[:,i])
new_array


[ 1  4  7 10]
[ 0.04545455  0.18181818  0.31818182  0.45454545]
[ 2  5  8 11]
[ 0.07692308  0.19230769  0.30769231  0.42307692]
[ 3  6  9 12]
[ 0.1  0.2  0.3  0.4]


array([[ 0.04545455,  0.07692308,  0.1       ],
       [ 0.18181818,  0.19230769,  0.2       ],
       [ 0.31818182,  0.30769231,  0.3       ],
       [ 0.45454545,  0.42307692,  0.4       ]])

0
[ 1  4  7 10]
1
[ 2  5  8 11]
2
[ 3  6  9 12]


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1]])

In [171]:
def parse_mat_matrix(filename, category, normalization=False):
    f = open(filename, 'r')
    lines = f.readlines()
    read = False
    for indx, line in enumerate(lines):
        if ';' in line:
            read = False
        if read:
            vector = line.split(' ')
            # parse out %
            comment_indx = vector.index('%')
            vector = vector[:comment_indx]
            matrix = np.vstack((matrix, vector))
        if category in line:
            read = True
            vector = lines[indx+1].split(' ')
            comment_indx = vector.index('%')
            length = len(vector[:comment_indx])
            matrix = np.empty(length)
    matrix = np.array(matrix[1:], dtype='float64')    
    
    if normalization:
        new_matrix = np.empty(np.shape(matrix))
        for i in range(np.shape(matrix)[1]):
            new_matrix[:,i] = normalize(matrix[:,i])
        return new_matrix[:-2]
    # no lost and total
    return matrix[:-2]


def parse_mat_name(filename):
    f = open(filename, 'r')
    lines = f.readlines()
    read = False
    names = []
    for line in lines:
        if ';' in line:
            read = False
        if read:
            iso = line.replace(' ', '').replace("'", '').strip()
            names.append(iso)
        if 'NAMES' in line:
            read = True
    return names[:-2]

def parse_mat_burnup(filename):
    f = open(filename, 'r')
    lines = f.readlines()
    for line in lines:
        if 'TOT_BURNUP' in line:
            bu = line.split()
            a = bu.index('[') + 1
            z = bu.index('];')
            bu = bu[a:z]
    return np.array(bu, dtype='float64') * 1e3

def name_and_matrix_to_dict(name_list, matrix):
    return_dict = {}
    for indx, val in enumerate(name_list):
        return_dict[val] = matrix[indx]
    return return_dict

def normalize(array):
    new_array = np.empty(len(array))
    for indx,val in enumerate(array):
        new_array[indx] = val / sum(array)
    return new_array

# def name_bu_matrix_to_df(name_list, bu_list, matrix):
    

In [172]:
mat = parse_mat_matrix('./serpent_test_burnup/case_1_enrichment_3.3%/pwr_dep.m', 'MAT_UO2_MDENS',
                       normalization=True)

In [173]:
name = parse_mat_name('./serpent_test_burnup/case_1_enrichment_3.3%/pwr_dep.m')

In [174]:
filename = './serpent_test_burnup/case_1_enrichment_3.3%/pwr_dep.m'
name_and_matrix_to_dict(name_list = parse_mat_name(filename),
                        matrix = parse_mat_matrix(filename, 'MAT_UO2_MDENS'))

{'H1': array([  0.00000000e+00,   2.88060000e-08,   3.04648000e-08,
          3.21088000e-08,   3.45472000e-08,   3.79990000e-08,
          3.86489000e-08,   3.86505000e-08,   3.86827000e-08,
          4.03594000e-08,   4.28146000e-08,   4.32009000e-08,
          4.43784000e-08,   4.60871000e-08,   5.07028000e-08,
          5.10102000e-08,   5.50312000e-08,   5.75869000e-08,
          6.90288000e-08,   6.90872000e-08,   6.92675000e-08]),
 'H2': array([  0.00000000e+00,   6.57853000e-09,   6.97100000e-09,
          7.35503000e-09,   7.92475000e-09,   8.73916000e-09,
          8.88785000e-09,   8.88821000e-09,   8.89562000e-09,
          9.28533000e-09,   9.86093000e-09,   9.95360000e-09,
          1.02275000e-08,   1.06305000e-08,   1.16221000e-08,
          1.16930000e-08,   1.26576000e-08,   1.32305000e-08,
          1.59258000e-08,   1.59393000e-08,   1.59808000e-08]),
 'H3': array([  0.00000000e+00,   5.86186000e-13,   6.44253000e-13,
          7.00506000e-13,   7.90740000e-13,   9.

In [175]:
# do it for all dep files
import os
subdirectory_list = [x[0] for x in os.walk('./serpent_test_burnup')][1:]
dir_dict = {}
for subdir in subdirectory_list:
    enr = subdir.split('_')[-1]
    enr = enr.replace('%', '')
    dir_dict[enr] =  subdir
dir_dict

{'3.3': './serpent_test_burnup/case_1_enrichment_3.3%',
 '4.9': './serpent_test_burnup/case_10_enrichment_4.9%',
 '4.1': './serpent_test_burnup/case_6_enrichment_4.1%',
 '3.2': './serpent_test_burnup/case_7_enrichment_3.2%',
 '4.7': './serpent_test_burnup/case_5_enrichment_4.7%',
 '4.6': './serpent_test_burnup/case_2_enrichment_4.6%',
 '3.5': './serpent_test_burnup/case_9_enrichment_3.5%',
 '3.9': './serpent_test_burnup/case_3_enrichment_3.9%',
 '3.7': './serpent_test_burnup/case_4_enrichment_3.7%',
 '3.6': './serpent_test_burnup/case_8_enrichment_3.6%'}

In [176]:
coll_dict = {}
first = True
for enr, path in dir_dict.items():
    filename = path + '/pwr_dep.m'
    name_matrix_dict = name_and_matrix_to_dict(name_list = parse_mat_name(filename),
                        matrix = parse_mat_matrix(filename, 'MAT_UO2_MDENS', normalization=True))
    name_matrix_dict['bu'] = parse_mat_burnup(filename)
    name_matrix_dict['enr'] = [enr] * len(bu)
    coll_dict[enr] = name_matrix_dict

In [177]:
enr_num = len(dir_dict.keys())
bu_num = len(parse_mat_burnup(filename))
print('TOTAL NUMBER OF DEPLETION CALCULATIONS SHOULD BE: \n'
      '[enrichment variation * burnup steps]\n'
      '%i * %i = %i'
%(enr_num, bu_num, enr_num * bu_num))

TOTAL NUMBER OF DEPLETION CALCULATIONS SHOULD BE: 
[enrichment variation * burnup steps]
10 * 21 = 210


In [178]:
df_dict = {}
first_key = list(coll_dict.keys())[0]
for category in coll_dict[first_key].keys():
    long_vec = np.empty(0)
    for key, val in coll_dict.items():
        long_vec = np.append(long_vec, val[category])
    df_dict[category] = long_vec

In [179]:
df = pd.DataFrame.from_dict(df_dict)

In [180]:
df

H1            H2            H3           He3       He4  \
0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000   
1    1.377841e-09  3.146625e-10  2.803829e-14  4.816703e-16  0.000002   
2    1.457197e-09  3.334380e-10  3.081601e-14  5.041223e-16  0.000002   
3    1.535848e-09  3.518103e-10  3.350703e-14  5.228487e-16  0.000002   
4    1.652502e-09  3.790658e-10  3.782359e-14  5.569549e-16  0.000002   
5    1.817643e-09  4.180288e-10  4.428398e-14  6.176132e-16  0.000002   
6    1.848733e-09  4.251419e-10  4.547349e-14  6.287690e-16  0.000002   
7    1.848810e-09  4.251590e-10  4.547640e-14  6.287881e-16  0.000002   
8    1.850350e-09  4.255136e-10  4.553792e-14  6.292044e-16  0.000002   
9    1.930569e-09  4.441586e-10  4.872608e-14  6.557911e-16  0.000002   
10   2.048034e-09  4.716970e-10  5.368228e-14  7.016524e-16  0.000003   
11   2.066514e-09  4.761301e-10  5.450316e-14  7.104592e-16  0.000003   
12   2.122845e-09  4.892336e-10  5.681232e-14  7.305425e-16  0.000003   
13   2.204598e-09  5.085149e-10  6.037362e-14  7.650135e-16  0.000003   
14   2.425438e-09  5.559591e-10  6.972008e-14  8.416905e-16  0.000003   
15   2.440143e-09  5.593508e-10  7.038501e-14  8.481581e-16  0.000003   
16   2.632538e-09  6.055040e-10  7.969341e-14  9.476356e-16  0.000003   
17   2.754820e-09  6.329156e-10  8.526434e-14  9.963715e-16  0.000004   
18   3.302301e-09  7.618819e-10  1.136431e-13  1.258121e-15  0.000005   
19   3.305096e-09  7.625280e-10  1.137881e-13  1.260049e-15  0.000005   
20   3.313722e-09  7.645135e-10  1.142417e-13  1.264900e-15  0.000005   
21   0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000   
22   1.181631e-09  2.623550e-10  2.256020e-14  6.047826e-16  0.000001   
23   1.243669e-09  2.765816e-10  2.476356e-14  6.291890e-16  0.000001   
24   1.307798e-09  2.909934e-10  2.689127e-14  6.543942e-16  0.000002   
25   1.403491e-09  3.121885e-10  3.030740e-14  6.944580e-16  0.000002   
26   1.535660e-09  3.425397e-10  3.562671e-14  7.571699e-16  0.000002   
27   1.559662e-09  3.480094e-10  3.653499e-14  7.680444e-16  0.000002   
28   1.559720e-09  3.480233e-10  3.653748e-14  7.680731e-16  0.000002   
29   1.560968e-09  3.483079e-10  3.658718e-14  7.686040e-16  0.000002   
..            ...           ...           ...           ...       ...   
180  1.990283e-09  4.537166e-10  5.201147e-14  7.442353e-16  0.000003   
181  2.068943e-09  4.714638e-10  5.542885e-14  7.742062e-16  0.000003   
182  2.286536e-09  5.196219e-10  6.471128e-14  8.645184e-16  0.000003   
183  2.300951e-09  5.229038e-10  6.534085e-14  8.695609e-16  0.000003   
184  2.486536e-09  5.661506e-10  7.418396e-14  9.518953e-16  0.000003   
185  2.607706e-09  5.942468e-10  8.020706e-14  1.013200e-15  0.000004   
186  3.169543e-09  7.197213e-10  1.089851e-13  1.276796e-15  0.000004   
187  3.172192e-09  7.203526e-10  1.091305e-13  1.278374e-15  0.000004   
188  3.180866e-09  7.223094e-10  1.095998e-13  1.282967e-15  0.000004   
189  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000   
190  1.362615e-09  3.015469e-10  2.663565e-14  5.053293e-16  0.000002   
191  1.436960e-09  3.184898e-10  2.915396e-14  5.216118e-16  0.000002   
192  1.511880e-09  3.359503e-10  3.182598e-14  5.421225e-16  0.000002   
193  1.625069e-09  3.612324e-10  3.582543e-14  5.743855e-16  0.000002   
194  1.787429e-09  3.979083e-10  4.183336e-14  6.351503e-16  0.000002   
195  1.816668e-09  4.047443e-10  4.302616e-14  6.462487e-16  0.000002   
196  1.816740e-09  4.047612e-10  4.302900e-14  6.462680e-16  0.000002   
197  1.818218e-09  4.050902e-10  4.308443e-14  6.466266e-16  0.000002   
198  1.895435e-09  4.224058e-10  4.600055e-14  6.692728e-16  0.000002   
199  2.007757e-09  4.493117e-10  5.074188e-14  7.159908e-16  0.000003   
200  2.024578e-09  4.533494e-10  5.150825e-14  7.228223e-16  0.000003   
201  2.078097e-09  4.654500e-10  5.367942e-14  7.407661e-16  0.000003   
202  2.156957e-09  4.834399e-10  5.698508e-14  7.710824e-16  0.000003   
